### ISSUE TITLE
dig into new API

### ISSUE THREAD

**Issue by sckott** [palaeoverse-community/rphylopic#23]
http://www.phylopic.org.s3-website-us-west-2.amazonaws.com/api/docs/2.0/

emailed asking about API keys and base url

**Comment by sckott** [comment]
still not up, whenever it comes out

**Comment by tmkeesey-ln** [comment]
It's up! http://api-docs.phylopic.org/2.0/

**Comment by sckott** [comment]
@tmkeesey-ln congrats on rolling out the new version!

**Comment by keesey** [comment]
Thanks -- let me know if I can help transition this package in any way. (Unfortunately I don't know R very well, but I can certainly advise on the new API.)

**Comment by keesey** [comment]
Heads up: I will be taking the API down from `phylopic.org` sometime soon, probably in the next month. I will try to keep it alive at `v1.phylopic.org` for a little while, probably no later than end of year.

**Comment by sckott** [comment]
ok, thanks. i'll try to get to this soon

**Comment by sckott** [comment]
@keesey i'm not sure i understand the `build` query parameter that I think is supposed to be supplied with all requests. How does one get the current build number? If only the accepted build number is allowed, then can this query parameter simply be dropped?

**Comment by keesey** [comment]
It's to help cacheing and make sure you're pulling from the same data build. If you leave it out, you'll get redirected to a URL with it. For list endpoints, don't include a page until you have the build number. (Generally best practice to call the list endpoint without a page before loading any pages.)

**Comment by levisimons** [comment]
Will rphylopic be updated to work with the new API?  The old API is now officially shut down.

**Comment by sckott** [comment]
@levisimons  see #35 - I don't use this pkg anymore, so ideally someone will take it over, or just start a new pkg if they prefer. i might be able to get to this but may be a while

**Comment by keesey** [comment]
[_PhyloPic 2.0_](https://www.phylopic.org) launched yesterday, so this package has probably stopped working.
