### ISSUE TITLE
Help wanted moving to new Phylopic API

### ISSUE THREAD

**Issue by sckott** [palaeoverse-community/rphylopic#35]
see issue #23 

Anyone that's contributed to this package or using it want to help move to the new API? Seems there's a bit of a time crunch, and I don't really have time right now. 

❤️

**Comment by sckott** [comment]
p.s., if you are interested, you can also take over the pkg completely as I don't use this pkg anymore, or work on it

**Comment by keesey** [comment]
I'd look into it, but I don't know R. Happy to help whoever ends up doing it with any questions about the new API, though!

**Comment by willgearty** [comment]
@sckott @keesey: @LewisAJones and I would be interested in migrating this to the new API and taking over maintenance as part of the [palaeoverse organization](https://github.com/palaeoverse-community).

**Comment by keesey** [comment]
Please reach out if you need help with the new API -- it's fairly different from v1: http://api-docs.phylopic.org/v2/

For some purposes it might be best used in tandem with another open API, particularly _[Open Tree of Life](https://opentreeoflife.github.io/)_ and _[The Paleobiology Database](https://paleobiodb.org/)_.

**Comment by sckott** [comment]
@willgearty sounds good. i'll see about how to transfer

**Comment by sckott** [comment]
i added you @willgearty - maybe you can transfer after that

**Comment by LewisAJones** [comment]
Thanks @sckott and @keesey! Let's keep in touch and thank you for all your efforts over the years! :clap:

**Comment by willgearty** [comment]
@sckott I think you to transfer ownership under the general settings?
![image](https://user-images.githubusercontent.com/7232514/218547726-b1bd0dcc-ba34-4094-9063-341fb72cc1fd.png)

**Comment by sckott** [comment]
i think you need to add me to your org, it's saying I can't transfer there

**Comment by willgearty** [comment]
I'd be happy to add you if you'd like, or you can feel free to transfer to my personal account, then I should be able to transfer to the org.

**Comment by willgearty** [comment]
All set, thanks @sckott!

**Comment by sckott** [comment]
👍🏽
