### ISSUE TITLE
Reimplement `image_list()`

### ISSUE THREAD

**Issue by rdinnager** [palaeoverse-community/rphylopic#38]
**Is your feature request related to a problem? Please describe.**
I wrote a package for making packed image mosaics (https://github.com/rdinnager/impac). I use phylopic images as an example on the readme (and automatically generate new images every week). To do this I used `rphylopic::image_list()` that used to exist as of the last version, but seems to no longer. I use it to get all image uuids available in the database and then randomly select some of them.

**Describe the solution you'd like**
Reimplement `image_list()`. Failing this, a function to grab a random image from Phylopic would work for my use case.

**Describe alternatives you've considered**
Can't think of any right now. I'm happy to implement myself and make a pull request if that would help.

**Comment by willgearty** [comment]
@rdinnager I just pushed a change to `get_uuid()` that allows you to specify `name = NULL`. This then returns `n` images from the database (with no taxonomic filtering). If you specify some arbitrarily large number, you'll get all of the uuids from the database (right now there are a total of 6771 images). Let us know if that's sufficient for your use case!

**Comment by rdinnager** [comment]
Thanks @willgearty ! Funnily enough, calling `get_uuid(name = NULL, n = 10000)` was the first thing I tried after I realised `image_list()` was gone, but it didn't work at the time. Thanks for adding this, it should do fine for my purposes. Thanks a lot to you and @LewisAJones for keeping this package alive, it would have been sad to lose it. I will close this issue.

**Comment by willgearty** [comment]
Glad to hear it! Let us know if there are any other features you'd like to see!
