### ISSUE TITLE
get_attribution

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/rphylopic#56]
Currently, attribution data is available via `get_attribution`. It could be useful to provide a token output which could be included in manuscripts/text, for example:

"Organism silhouette from PhyloPic (Michael Keesey, 2023), created by John Smith (2023)."

**Comment by willgearty** [comment]
Oh, if you provide a list of uuids it should provide a nice little paragraph for you!

**Comment by LewisAJones** [comment]
Precisely! The [grateful](https://github.com/Pakillo/grateful) package got me thinking along these lines... so it could be a nice addition.

**Comment by LewisAJones** [comment]
This is going to be easy to implement for names of creators and the year created. What do you think we should do about the licenses? Do we provide the link or scrape the license type? Or have some code for matching the link with the license type?
