### ISSUE TITLE
custom legend icons for geom_phylopic

### ISSUE THREAD

**Issue by willgearty** [palaeoverse-community/rphylopic#57]
@LewisAJones requests that legends related to `geom_phylopic` should use the silhouettes instead of points

**Comment by willgearty** [comment]
I've been bashing my head against a wall trying to get this to work, but I'm not making any progress on this. I was originally trying to treat img as an aesthetic, so the legend could then have different silhouettes in it. However, it appears that that isn't possible with the way ggplot handles the rendering of legends.

However, I _think_ I can make it such that the user can specify a silhouette to be used for the entire legend. This obviously wouldn't be that useful for plots with multiple different silhouettes, but could be very useful and aesthetically pleasing for plots with just a single unique silhouette.

**Comment by willgearty** [comment]
It might even be possible that, if only one unique silhouette is used in a plot, we just use that one automatically.

**Comment by LewisAJones** [comment]
Hmm... this should be relatively straightforward to implement. Ultimately, what we want to achieve is just changing the glyph in a legend. 

I think the best way to do this is implementing a `draw_key_phylopic`. This [tutorial](https://www.emilhvitfeldt.com/post/changing-glyph-in-ggplot2/) shows an example of doing this with a smiley face. Maybe start there?

**Comment by willgearty** [comment]
Yes, it's straightforward to have a single custom image, but not straightforward to have the images be based on the images in the plot itself.

**Comment by willgearty** [comment]
After many attempts to make this automated, I've resorted to implementing a manual method for users to specify the silhouettes in the legend in the `legend-keys` branch. Have a look when you get a chance @LewisAJones.

**Comment by willgearty** [comment]
Some more information: the new method uses a package environment to store data between legend key generations. Unfortunately, this doesn't work for transferring information from the geom renderer to the legend renderer because the legend gets rendered first (ugh).
