### ISSUE TITLE
Problem with R ver 4.3 

### ISSUE THREAD

**Issue by bserranito** [palaeoverse-community/rphylopic#70]
**Describe the bug**
"Although it was functioning correctly in the past with ggplot2, the most recent update of R (ver 4.3) has resulted in the following error:

"Error in add_phylopic(img = img_Lsceler, color = "black", alpha = 0.7) : 
  argument "x" is missing, with no default"

**To Reproduce**
uuid_Lsceler <- get_uuid(name = "Lagocephalus sceleratus", n = 1)
get_attribution(uuid = uuid_Lsceler)
img_Lsceler <- get_phylopic(uuid = uuid_Lsceler)

Lsceler_p1=ggplot() +
  add_phylopic(img = img_Lsceler, color = "black", alpha = .7) +
  theme_bw()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - palaeoverse version : 1.1.1
 - R Version : 4.3
- ggplot2 version : 3.4.2

**Comment by willgearty** [comment]
Thanks for reporting this @bserranito. As of rphylopic v. 1.1.0, `add_phylopic()` now requires the `x` and `y` arguments to be specified because of internal changes to the function (https://github.com/palaeoverse-community/rphylopic/pull/48). Apologies if this was not clear.

**Comment by bserranito** [comment]
Thanks @willgearty for your prompt response. Indeed, i missed the update of the package.
It's working now!
