### ISSUE TITLE
On load message

### ISSUE THREAD

**Issue by LewisAJones** [palaeoverse-community/rphylopic#85]
Currently, we have an on load message which is super useful, but a little long:

```Thank you for using rphylopic! Don't forget to attribute the silhouettes that you use to their contributors using the `get_attribution()` function and/or the `verbose` argument in the `geom_phylopic()`, `add_phylopic()`, and `add_phylopic_base()` functions. We would also appreciate it if you cite this package in your work (use `citation("rphylopic")`).```

We should try to shorten it, perhaps something like:

```You are using rphylopic 1.2.0. Please remember to credit PhyloPic contributors (hint: `get_attribution()`) and cite rphylopic in your work (hint: `citation("rphylopic")`).```

**Comment by willgearty** [comment]
Fixed by 585050a.
